name: Deploy Chatbot By Self Runner

on:
  push:
    branches: ['**']

jobs:
  deploy:
    runs-on: [self-hosted, linux, chatbot_runner]

    steps:
      - name: Update service
        run: |
          cd /home/stadmin/ChatBotPlatform
          git checkout main
          git pull
          cd ..
          ./restart_chatbot.sh main clear
